import Head from "next/head";
import Image from "next/image";
import { Menu } from "@/componentes/Menu";
// import { LivroLista }

export default function Home() {
  return (
    <>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favcon.ico" />
      </Head>
      <Menu />
      <main className="container-fluid">
        <h1 className="h1 mx-auto">Página Inicial</h1>
      </main>
    </>
  );
}
