import { Menu } from "@/componentes/Menu";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/componentes/LivroLinha";
import { ControleLivro, LivroMongo } from "@/classes/controle/ControleLivros";

const LivroLista: NextPage = () => { 
    
    const controleLivro = new ControleLivro();
    
    const [livros,setLivros] = useState(Array<LivroMongo>)
    const [carregado,setCarregado] = useState(false)
    
    useEffect( () => {
        controleLivro.obterLivros().then( lista => {
            setLivros(lista);
        }).finally( () => setCarregado(true));
    },[carregado])
    

    const excluir = async( codigo:string ) => {
        controleLivro.excluir(codigo).then( ()=> {
            setCarregado(false);
        } )
    }

    return (
        <div>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favcon.ico" />
            </Head>
            <Menu/>
            <main>
                <div className="container py-3">

                <h1 className="h1">Catálogo de Livros</h1>
                <table className="table">
                <thead className="table-dark">
                    <tr>
                        <th scope="col"> Título </th>
                        <th scope="col"> Resumo </th>
                        <th scope="col"> Editora </th>
                        <th scope="col"> Autores </th>
                    </tr>
                </thead>
                <tbody className="table-striped"> 
                    {livros.map( (livro:Livro, index:number) => {
                        return ( <LinhaLivro key={index} livro={livro} excluir={excluir}></LinhaLivro>)
                    })}
                </tbody>
                </table>
                    </div>
            </main>
        </div>
    )}
    
export default LivroLista